steps:
- name: node:20.5.1
  entrypoint: npm
  args: ["install"]
# build the frontend
- name: node:20.5.1
  entrypoint: npm
  args: ["run", "build-only"]
# copy build output to the GCS buck-ets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ["gsutil", "ls"]
timeout: "1600s"