steps:
- name: node:20.5.1
  entrypoint: npm
  args: ["install"]
# build the frontend
- name: node:20.5.1
  entrypoint: npm
  args: ["run", "build-only"]
# copy build output to the GCS bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ["gsutil", "-q", "stat", "build/*"]
timeout: "1600s"