steps:
- name: node:14
  entrypoint: npm
  args: ['install']

# Debugging step to print current directory and list files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - 'pwd && ls -l'

# build the frontend
- name: node:14
  entrypoint: npm
  args: ['run', 'build-only']

# copy build output to the GCS buck-ets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'dist/*', 'gs://gcsbucketdefrr/']
timeout: "1600s"