steps:
- name: node:20.5.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build-only"]
# copy build output to the GCS bucket
- name: 'gcr.io/cloud-builders/gcloud'
  args: ["gsutil", "cp", "-r", "build/*", "gs://gcsbucketdefrr"]
timeout: "1600s"