steps:
- name: node
  entrypoint: npm
  args: ['install']

- name: node
  entrypoint: npm
  args: ['install', 'vue-router@4']

- name: node
  entrypoint: npm
  args: ['install', 'axios']

  # Debugging step to print current directory and list files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - 'pwd && ls -l'

# build the frontend
- name: node
  entrypoint: npm
  args: ['run', 'build-only']

# copy build output to the GCS buck-ets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'dist/*', 'gs://gcsbucketdefrr/']

# Apply service and deployment YAML files
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - apply
  - -f
  - service.yaml
  - -f
  - deployment.yaml

timeout: "1600s"